version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    volumes:
      - .:/app   # монтируем текущую папку, чтобы миграции сохранялись на хосте
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/finance_db
      SECRET_KEY: any_secret_key_for_migration
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic revision --autogenerate -m 'initial' && alembic upgrade head"